### ISSUE TITLE
Early exploration

### ISSUE THREAD

**Issue by oliviertassinari** [styils/styils#161]
Hi @zoy-l I'm following up on your comment from https://github.com/mui/material-ui/issues/34826#issuecomment-1314663275. 

I think that it could be interesting for this project to explore:

1. How would React Server Side component compatibility look like, e.g. maybe starting with Next.js 13 beta app folder. This might be a big one for MUI as developers might pick, e.g. Tailwind CSS only because it's compatible.
2. The `import { createSystem } from '@styils/[frame]'` API looks like something that we miss with MUI from emotion, it leads to a lot of complexity, e.g. https://mui.com/joy-ui/guides/using-joy-ui-and-material-ui-together/ cc @siriwatknp.
3. What allows the gain of performance compared to emotion? Meaning, what's the catch? It seems to be about forbidding to use style = f(prop). Instead, we have to use CSS variables or the theme. It sounds close to JSS. 
4. Maybe we could try the equivalent of https://github.com/mui/material-ui/pull/27776.
5. How would we implement something like this: https://mui.com/system/getting-started/the-sx-prop/?

Thanks :)

**Comment by zoy-l** [comment]
1. The React server component may not be able to reply to you for the time being. I don’t know much about it at the moment. The current result does not support it. need to try
2. createSystem is the solution I don't want to write type... roughly where themes and utilities are created
3.
 - Different styles are created only once and depend on theme patterns rather than CSS rule keys. In theory, there is only a certain performance overhead during initialization, so after the first creation is completed, subsequent style changes (initializing past theme changes) will only change the className or style, and will not parse CSS rules again
 - not depend on react lifecycle creation rules. theoretically the theme does not use var, It's okay, it is safe to use ':xxx-child'
 - don't need to write rules like `(...) (size === 'xxx' && {}))` and rules like `shouldForwardProp`
 - Passing values ​​through props, I think this is a trap written. Multiple choices can confuse people. Not everyone understands the logic behind whether to use style or prop. Using prop directly will generate a large number of roughly the same CSS rules. Passing a value is a state change that can be resolved with "variants". Values ​​that need to change frequently should use "vars"

4. yes, I will try, it should be a fun challenge
5. sx can be achieved by exporting 'styleSheet' and 'parseRules'

**Comment by zoy-l** [comment]
@oliviertassinari [next13 server-component demo](https://github.com/styils/next13-demo)

server components, as if there is not much difference between server rendering, except that cannot use 'context', to use themes, need to implement it in a different way..

**Comment by oliviertassinari** [comment]
> if there is not much difference between server rendering, except that cannot use context, to use themes, need to implement it in a different way.

Interesting
